from enum import Enum

class UserType(str, Enum):
    ADMIN = "ADMIN"
    CONTRACTOR = "CONTRACTOR"
    REGISTERED_USER = "REGISTERED_USER"
    CONTRACTED_SERVICE_PROVIDER_USER = "CONTRACTED_SERVICE_PROVIDER_USER"
    PARTNER_USER = "PARTNER_USER"
    PRACTICE_MANAGER = "PRACTICE_MANAGER"
    INTERNAL = "INTERNAL"  # Add the missing INTERNAL user type
